services:
    client:
        image: dns
        dns: 
            -172.20.0.2
        command: sleep 1000
        networks:
            letscode-net:
                ipv4_address: 172.20.0.3
        depends_on:
            - dns-server
            - target
    target:
        image: dns
        dns: 
            -172.20.0.2
        command: sleep 1000
        networks:
            letscode-net:
                ipv4_address: 172.20.0.4
    dns-server:
        image: internetsystemsconsortium/bind9:9.16
        expose:
            - 53/udp
            - 53/tcp
            - 953/tcp
        networks:
            letscode-net:
                ipv4_address: 172.20.0.2

networks:
    letscode-net:
        external: true

    

