version: "3.3"
services: 
    traefik:
        image: "traefik:v2.4"
        restart: always
        command: 
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbyedefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "3000:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            letscode-net:
networks:
    letscode-net:
            external:  true
